// Generated by gencpp from file projeto_15/CameraRequest.msg
// DO NOT EDIT!


#ifndef PROJETO_15_MESSAGE_CAMERAREQUEST_H
#define PROJETO_15_MESSAGE_CAMERAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace projeto_15
{
template <class ContainerAllocator>
struct CameraRequest_
{
  typedef CameraRequest_<ContainerAllocator> Type;

  CameraRequest_()
    {
    }
  CameraRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::projeto_15::CameraRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::projeto_15::CameraRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraRequest_

typedef ::projeto_15::CameraRequest_<std::allocator<void> > CameraRequest;

typedef boost::shared_ptr< ::projeto_15::CameraRequest > CameraRequestPtr;
typedef boost::shared_ptr< ::projeto_15::CameraRequest const> CameraRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::projeto_15::CameraRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::projeto_15::CameraRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace projeto_15

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::projeto_15::CameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projeto_15::CameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projeto_15::CameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projeto_15::CameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projeto_15::CameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projeto_15::CameraRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::projeto_15::CameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::projeto_15::CameraRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::projeto_15::CameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "projeto_15/CameraRequest";
  }

  static const char* value(const ::projeto_15::CameraRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::projeto_15::CameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::projeto_15::CameraRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::projeto_15::CameraRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::projeto_15::CameraRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::projeto_15::CameraRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PROJETO_15_MESSAGE_CAMERAREQUEST_H
