// Generated by gencpp from file projeto_15/Camera.msg
// DO NOT EDIT!


#ifndef PROJETO_15_MESSAGE_CAMERA_H
#define PROJETO_15_MESSAGE_CAMERA_H

#include <ros/service_traits.h>


#include <projeto_15/CameraRequest.h>
#include <projeto_15/CameraResponse.h>


namespace projeto_15
{

struct Camera
{

typedef CameraRequest Request;
typedef CameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Camera
} // namespace projeto_15


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::projeto_15::Camera > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::projeto_15::Camera&) { return value(); }
};

template<>
struct DataType< ::projeto_15::Camera > {
  static const char* value()
  {
    return "projeto_15/Camera";
  }

  static const char* value(const ::projeto_15::Camera&) { return value(); }
};


// service_traits::MD5Sum< ::projeto_15::CameraRequest> should match
// service_traits::MD5Sum< ::projeto_15::Camera >
template<>
struct MD5Sum< ::projeto_15::CameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::projeto_15::Camera >::value();
  }
  static const char* value(const ::projeto_15::CameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::projeto_15::CameraRequest> should match
// service_traits::DataType< ::projeto_15::Camera >
template<>
struct DataType< ::projeto_15::CameraRequest>
{
  static const char* value()
  {
    return DataType< ::projeto_15::Camera >::value();
  }
  static const char* value(const ::projeto_15::CameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::projeto_15::CameraResponse> should match
// service_traits::MD5Sum< ::projeto_15::Camera >
template<>
struct MD5Sum< ::projeto_15::CameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::projeto_15::Camera >::value();
  }
  static const char* value(const ::projeto_15::CameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::projeto_15::CameraResponse> should match
// service_traits::DataType< ::projeto_15::Camera >
template<>
struct DataType< ::projeto_15::CameraResponse>
{
  static const char* value()
  {
    return DataType< ::projeto_15::Camera >::value();
  }
  static const char* value(const ::projeto_15::CameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJETO_15_MESSAGE_CAMERA_H
